export const APARTMENT_DEFAULT = {
  list: [],
  total: 0,
  type: ''
}

export const SHOW_APARTMENT = 'SHOW_APARTMENT'
export const SET_HOT_SEARCH = 'SET_HOT_SEARCH'
export const SET_APARTMENT_LIST = 'SET_APARTMENT_LIST'
export const SET_RECOMMEND_APARTMENT = 'SET_RECOMMEND_APARTMENT'
export const UPDATE_APARTMENT_FAVORITE = 'UPDATE_APARTMENT_FAVORITE'
export const SET_NEXT_PAGE_APARTMENT_LIST = 'SET_NEXT_PAGE_APARTMENT_LIST'

/**
 * 公寓类型
 * 1.主页里的公寓列表
 * 2.心愿单里面的户型
 * 3.心愿单里面的公寓
 * 4.商圈集合的公寓
 * 5.活动集合的公寓
 * 6.看了又看的公寓
 * 7.搜索相关的公寓
 * 8.文章详情的公寓
 */
export const TYPE_SEARCH_APARTMENT = 'TYPE_SEARCH_APARTMENT'
export const TYPE_RECOMMEND_APARTMENT = 'TYPE_RECOMMEND_APARTMENT'
export const TYPE_CBD_APARTMENT = 'TYPE_CBD_APARTMENT'
export const TYPE_ACTIVITY_APARTMENT = 'TYPE_ACTIVITY_APARTMENT'
export const TYPE_NORMAL_APARTMENT = 'TYPE_NORMAL_APARTMENT'
export const TYPE_ARTICLE_APARTMENT = 'TYPE_ARTICLE_APARTMENT'
export const TYPE_FAVORITE_APARTMENT = 'TYPE_FAVORITE_APARTMENT'
export const TYPE_FAVORITE_HOUSE_TYPE = 'TYPE_FAVORITE_HOUSE_TYPE'

